spring:
  profiles:
    active:
      - local
      - secret
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true

--- # local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  origin: http://localhost:8080
logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
          datasource:
            init:
              ScriptUtils: debug

--- # spring1
spring:
  config:
    activate:
      on-profile: spring1
    import: secrets/application-env.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  origin: https://api.youngcha.team
logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
          datasource:
            init:
              ScriptUtils: debug

--- # spring2
spring:
  config:
    activate:
      on-profile: spring2
    import: secrets/application-env.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  origin: https://api.youngcha.team
logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
          datasource:
            init:
              ScriptUtils: debug
