version: "3.9"

services:
  spring1:
    container_name: spring1
    restart: always
    image: img
    environment:
      SERVER_MODE: prod
    ports:
      - "8081:8080"
    depends_on:
      - nginx
    networks:
      - youngcha

  spring2:
    container_name: spring2
    restart: always
    image: img
    environment:
      SERVER_MODE: prod
    ports:
      - "8082:8080"
    depends_on:
      - nginx
    networks:
      - youngcha

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80/tcp"
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/conf.d/application.conf:/etc/nginx/conf.d/application.conf
      - ~/nginx/conf.d/service-url.inc:/etc/nginx/conf.d/service-url.inc
    environment:
      - TZ=Asia/Seoul
    networks:
      - youngcha

networks:
  youngcha:
    driver: bridge