name: be-cd

on:
  push:
    branches:
      - dev/be

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create secret file
        run: |
          mkdir src/main/resources/secrets
          echo "${{ secrets.APPLICATION_ENV }}" > src/main/resources/secrets/application-env.yml

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ "$(docker ps -aqf name="^spring$")" ];
            then
              echo "> spring container 제거"
              docker stop spring
              docker rm spring
            else
              echo "> 구동 중인 spring container가 없으므로 종료하지 않습니다."
            fi
            
            if [[ "$(docker images -q ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest 2> /dev/null)" != "" ]]; then
              echo "> latest image 삭제"
              docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            fi
            
            echo "> docker compose up"
            docker compose up -d --build spring
        
            docker image prune -f